name: generate animation

on:
  schedule:
      - cron: '0 */12 * * *'
  workflow_dispatch:
  push:
    branches:
      - Fluxos-hidrológicos

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: platane/snk@v3
        id: snake-gif
        with:
          github_user_name: patrick9kk
          outputs: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
